In [2]:
import os
import pandas as pd

# Chemin du dossier à analyser
dossier = 'data/raw/'
liste_fichiers = []

for fichier in os.listdir(dossier):
    chemin_complet = os.path.join(dossier, fichier)
    if os.path.isfile(chemin_complet):
        nom_sans_ext = os.path.splitext(fichier)[0]
        if len(nom_sans_ext) >= 4 and nom_sans_ext[-4:].isdigit():
            annee = int(nom_sans_ext[-4:])
            nom_restant = nom_sans_ext[:-4]
        else:
            annee = None
            nom_restant = nom_sans_ext

        try:
            df_listing_temp = pd.read_csv(chemin_complet, nrows=0, encoding='ISO-8859-1')
            headers = list(df_listing_temp.columns)
        except Exception as e:
            print(f"⚠️ Erreur lecture header pour {fichier} : {e}")
            headers = []

        liste_fichiers.append({
            'fichier': fichier,
            'annee': annee,
            'fichier_categorie': nom_restant,
            'path': chemin_complet,
            'header': headers
        })

df_listing = pd.DataFrame(liste_fichiers)
df_listing = df_listing.dropna(subset=['annee'])
df_listing['annee'] = df_listing['annee'].astype(int)
print(df_listing.head())

                     fichier  annee  fichier_categorie  \
0            caract-2023.csv   2023            caract-
1  caracteristiques-2017.csv   2017  caracteristiques-
2  caracteristiques-2018.csv   2018  caracteristiques-
3  caracteristiques-2019.csv   2019  caracteristiques-
4  caracteristiques-2020.csv   2020  caracteristiques-

                                 path  \
0            data/raw/caract-2023.csv
1  data/raw/caracteristiques-2017.csv
2  data/raw/caracteristiques-2018.csv
3  data/raw/caracteristiques-2019.csv
4  data/raw/caracteristiques-2020.csv

                                              header
0  [Num_Acc;"jour";"mois";"an";"hrmn";"lum";"dep"...
1  [Num_Acc, an, mois, jour, hrmn, lum, agg, int,...
2  [Num_Acc, an, mois, jour, hrmn, lum, agg, int,...
3  [Num_Acc;"jour";"mois";"an";"hrmn";"lum";"dep"...
4  [Num_Acc;"jour";"mois";"an";"hrmn";"lum";"dep"...

In [3]:
df_listing[df_listing['annee'] == 2020]

,fichier,annee,fichier_categorie,path,header
4,caracteristiques-2020.csv,2020,caracteristiques-,data/raw/caracteristiques-2020.csv,"[Num_Acc;""jour"";""mois"";""an"";""hrmn"";""lum"";""dep""..."
22,lieux-2020.csv,2020,lieux-,data/raw/lieux-2020.csv,"[Num_Acc;""catr"";""voie"";""v1"";""v2"";""circ"";""nbv"";..."
43,usagers-2020.csv,2020,usagers-,data/raw/usagers-2020.csv,"[Num_Acc;""id_vehicule"";""num_veh"";""place"";""catu..."
62,vehicules-2020.csv,2020,vehicules-,data/raw/vehicules-2020.csv,"[Num_Acc;""id_vehicule"";""num_veh"";""senc"";""catv""..."

In [4]:
#homogénéisation de la colonne fichier_categorie
df_listing['fichier_categorie'] = df_listing['fichier_categorie'].replace('lieux-', 'lieux_')
df_listing['fichier_categorie'] = df_listing['fichier_categorie'].replace('usagers-', 'usagers_')
df_listing['fichier_categorie'] = df_listing['fichier_categorie'].replace('vehicules-', 'vehicules_')
df_listing.loc[df_listing['fichier_categorie'].isin(['caract-', 'caracteristiques-', 'carcteristiques-']), 'fichier_categorie'] = 'caracteristiques_'
df_listing.loc[df_listing['fichier_categorie'].isin(['lieux-', 'caracteristiques-', 'carcteristiques']), 'fichier_categorie'] = 'caracteristiques_'
print(df_listing['fichier_categorie'].drop_duplicates())

0     caracteristiques_
19               lieux_
40             usagers_
59           vehicules_
Name: fichier_categorie, dtype: object

In [5]:
print(df_listing['header'].drop_duplicates())

0     [Num_Acc;"jour";"mois";"an";"hrmn";"lum";"dep"...
1     [Num_Acc, an, mois, jour, hrmn, lum, agg, int,...
9     [Num_Acc\tan\tmois\tjour\thrmn\tlum\tagg\tint\...
18    [Accident_Id;"jour";"mois";"an";"hrmn";"lum";"...
19    [Num_Acc, catr, voie, v1, v2, circ, nbv, pr, p...
21    [Num_Acc;"catr";"voie";"v1";"v2";"circ";"nbv";...
40    [Num_Acc, place, catu, grav, sexe, trajet, sec...
42    [Num_Acc;"id_vehicule";"num_veh";"place";"catu...
44    [Num_Acc;"id_usager";"id_vehicule";"num_veh";"...
59    [Num_Acc, senc, catv, occutc, obs, obsm, choc,...
61    [Num_Acc;"id_vehicule";"num_veh";"senc";"catv"...
Name: header, dtype: object

In [6]:
#enregistrement du listing de fichier + header
# 
df_listing.to_csv("data/processed/listingfiles.csv", index=False,)

In [17]:
import pandas as pd

def get_data(Annee, Cat, df_listing):
    ligne = df_listing.loc[(df_listing["annee"] == int(Annee)) & (df_listing["fichier_categorie"] == Cat), "path"]
    header = df_listing.loc[(df_listing["annee"] == int(Annee)) & (df_listing["fichier_categorie"] == Cat), "header"]
    
    if not ligne.empty:
        chemin = ligne.iloc[0]
        header_val = header.iloc[0]
        
       
       
        # Si header_val est une chaîne de colonnes séparées, on teste le séparateur sur cette chaîne
        if ';' in header_val[0]:
            sep = ';'
        elif '\t' in header_val[0]:
            sep = '\t'
        else:
            sep = ','
        print("sep=",sep)
        for enc in ['utf-8', 'cp1252', 'iso-8859-1','latin-1']:
            print(chemin, sep, enc)
            try:
                print(f"Essai avec encodage : {enc}")
                """
                 # Lecture brute des premières lignes pour détecter les anomalies (ex: guillemets doubles)
                with open(chemin, 'r', encoding=enc, errors='replace') as f:
                    preview = [next(f) for _ in range(10)]
                preview_text = ''.join(preview)
                contient_guillemets_doubles = '""' in preview_text

                # Si anomalie détectée, nettoyage manuel ligne par ligne
                if contient_guillemets_doubles:
                    print("⚠️ Fichier suspect, tentative de nettoyage manuel")
                    with open(chemin, 'r', encoding=enc, errors='replace') as f:
                        lignes_nettoyees = [ligne.replace('""', '"').strip() for ligne in f]
                    contenu_nettoye = StringIO('\n'.join(lignes_nettoyees))
                    df_listing_read = pd.read_csv(contenu_nettoye, sep=sep, quotechar='"', low_memory=False)
                    df_listing_read.columns = df_listing_read.columns.str.replace('"', '').str.strip()
                else:
                    # Lecture standard si aucun problème détecté
                """
                df_listing_read = pd.read_csv(chemin, sep=sep, encoding=enc, low_memory=False)
                print(chemin, sep, enc)
                print(f"✅ Lecture réussie avec {enc}")
                return df_listing_read
            
            except FileNotFoundError:
                print(f"    ❌ Fichier non trouvé : {chemin}")
                return pd.DataFrame()
            except UnicodeDecodeError as e:
                print(f"    ⚠️ Échec avec {enc} : {e}")
            except Exception as e:
                print(f"    ❌ Autre erreur avec {enc} : {e}")
        
        # Si aucun encodage ne marche
        print(f"❌ Impossible de lire le fichier {chemin} avec les encodages testés.")
        return pd.DataFrame()
    else:
        print(f"❌ Aucune configuration trouvée pour année={Annee}, catégorie={Cat}")
        return pd.DataFrame()

In [18]:
#get_data(2009, 'caracteristiques_', df_listing)

sep=
data/raw/caracteristiques_2009.csv 	 utf-8
Essai avec encodage : utf-8
data/raw/caracteristiques_2009.csv 	 utf-8
✅ Lecture réussie avec utf-8

,Num_Acc,an,mois,jour,hrmn,lum,agg,int,atm,col,com,adr,gps,lat,long,dep
0,200900000001,9,1,30,2030,3,1,1,1.0,6,67,RTE DE GU�MEN�,M,0.0,0,440
1,200900000002,9,1,17,300,3,1,1,1.0,3,17,LE BOIS JOLI,M,0.0,0,440
2,200900000003,9,1,29,645,3,1,1,1.0,3,52,NaN,M,0.0,0,440
3,200900000004,9,1,4,615,3,1,1,9.0,6,44,LE BECO,M,0.0,0,440
4,200900000005,9,1,16,1500,1,1,1,1.0,7,36,MOULIN DE LA GARENNE,M,0.0,0,440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74404,200900074719,9,11,17,1740,1,1,1,1.0,2,13,AUTOROUTE A1,NaN,NaN,NaN,972
74405,200900074720,9,11,21,2100,3,1,1,1.0,2,13,ROUTE NATIONALE 1,NaN,NaN,NaN,972
74406,200900074721,9,11,1,1120,1,1,1,1.0,5,13,ROUTE DEPARTEMENTALE 3,NaN,NaN,NaN,972
74407,200900074722,9,11,8,1540,1,2,1,1.0,7,9,DU PONT (RUE),NaN,NaN,NaN,974
74408,200900074898,9,4,3,1225,1,1,3,1.0,3,2,"2407, EBOUE (ROCADE FELI",NaN,NaN,NaN,973

In [8]:
def get_annee_dispo(annees_list, annee_min, annee_max):
    """
    trie une liste d'année en tenant compte d'un mini et d'un maxi
    ex: print(get_annee_dispo(df['annee'],'2020','2021'))
    """
    import pandas as pd

    def safe_int(value):
        try:
            return int(value)
        except (ValueError, TypeError):
            return None

    annee_min = safe_int(annee_min)
    annee_max = safe_int(annee_max)

    # Nettoyage ici, sur la série brute
    annees = pd.to_numeric(annees_list, errors='coerce').dropna().astype(int)

    if annee_min is not None and annee_max is not None:
        annees = annees[annees.between(annee_min, annee_max)]
    elif annee_min is not None:
        annees = annees[annees >= annee_min]
    elif annee_max is not None:
        annees = annees[annees <= annee_max]

    return annees.drop_duplicates().sort_values(ascending=False).reset_index(drop=True)

# Utilisation
#print(list_annee)

In [9]:
#df_listing.head(15)

,fichier,annee,fichier_categorie,path,header
0,caract-2023.csv,2023,caracteristiques_,data/raw/caract-2023.csv,"[Num_Acc;""jour"";""mois"";""an"";""hrmn"";""lum"";""dep""..."
1,caracteristiques-2017.csv,2017,caracteristiques_,data/raw/caracteristiques-2017.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
2,caracteristiques-2018.csv,2018,caracteristiques_,data/raw/caracteristiques-2018.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
3,caracteristiques-2019.csv,2019,caracteristiques_,data/raw/caracteristiques-2019.csv,"[Num_Acc;""jour"";""mois"";""an"";""hrmn"";""lum"";""dep""..."
4,caracteristiques-2020.csv,2020,caracteristiques_,data/raw/caracteristiques-2020.csv,"[Num_Acc;""jour"";""mois"";""an"";""hrmn"";""lum"";""dep""..."
5,caracteristiques_2005.csv,2005,caracteristiques_,data/raw/caracteristiques_2005.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
6,caracteristiques_2006.csv,2006,caracteristiques_,data/raw/caracteristiques_2006.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
7,caracteristiques_2007.csv,2007,caracteristiques_,data/raw/caracteristiques_2007.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
8,caracteristiques_2008.csv,2008,caracteristiques_,data/raw/caracteristiques_2008.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
9,caracteristiques_2009.csv,2009,caracteristiques_,data/raw/caracteristiques_2009.csv,[Num_Acc\tan\tmois\tjour\thrmn\tlum\tagg\tint\...
10,caracteristiques_2010.csv,2010,caracteristiques_,data/raw/caracteristiques_2010.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
11,caracteristiques_2011.csv,2011,caracteristiques_,data/raw/caracteristiques_2011.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
12,caracteristiques_2012.csv,2012,caracteristiques_,data/raw/caracteristiques_2012.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
13,caracteristiques_2013.csv,2013,caracteristiques_,data/raw/caracteristiques_2013.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."
14,caracteristiques_2014.csv,2014,caracteristiques_,data/raw/caracteristiques_2014.csv,"[Num_Acc, an, mois, jour, hrmn, lum, agg, int,..."

In [ ]:
#annee_dispo = get_annee_dispo(df_listing['annee'], 2016, 2022)

In [11]:
#get_annee_dispo(df_listing['annee'], 2016, 2022)

0    2022
1    2021
2    2020
3    2019
4    2018
5    2017
6    2016
Name: annee, dtype: int32

In [27]:
get_annee_dispo(df_listing['annee'], 2005, 2023)

0     2023
1     2022
2     2021
3     2020
4     2019
5     2018
6     2017
7     2016
8     2015
9     2014
10    2013
11    2012
12    2011
13    2010
14    2009
15    2008
16    2007
17    2006
18    2005
Name: annee, dtype: int32

In [39]:
all_accidents = []
from io import StringIO

# Récupérer les années disponibles dans la colonne 'annee'
annee_dispo = get_annee_dispo(df_listing['annee'], 2005, 2023)

for annee in annee_dispo:
    # On ouvre les fichiers
    print(f"\nTraitement des fichiers pour l'année {annee}...")
    caract = get_data(annee, 'caracteristiques_', df_listing)
    lieux = get_data(annee, 'lieux_', df_listing)
    usagers= get_data(annee, 'usagers_', df_listing)
    vehicules= get_data(annee, 'vehicules_', df_listing)
    # homogenisation colonne Num_acc
    if 'Accident_Id' in caract.columns:
        caract = caract.rename(columns={'Accident_Id': 'Num_Acc'})
    try:
        if 'id_vehicule' not in caract.columns:
                # merge des différentes tables avec gestion des erreurs 
            merged= (usagers
                .merge(lieux, on='Num_Acc')
                .merge(vehicules, on=['Num_Acc', 'id_vehicule'], how='inner')
                .merge(caract, on='Num_Acc')
            )
            all_accidents.append(merged)
            print(f"    ✅Fusion réussie pour l'année {annee}")
            continue
    except KeyError as e:
        print(f"    ⚠️ Clé manquante pour la fusion avec id_vehicule : {e}")
    # Tentative 2 : fusion sans id_vehicule
    try:
        if 'id_vehicule' not in caract.columns:
            merged = (usagers
                    .merge(lieux, on='Num_Acc')
                    .merge(vehicules, on=['Num_Acc', 'num_veh'], how='inner')
                    .merge(caract, on='Num_Acc')
                    )
            all_accidents.append(merged)
            print(f"    ✅Fusion réussie SANS id_vehicule pour l'année {annee}")


    except KeyError as e:
        print(f"    Erreur : colonne manquante {e}")
    except Exception as e:
        print(f"    Erreur lors de la fusion : {e}")  
    print(f"accident{annee}")
#On concatène    
if  all_accidents: 
    combined_data = pd.concat(all_accidents, ignore_index=True)
    #on drop duplicate car on ne s'explique pas pourquoi il y en a
    #combined_data = combined_data.drop_duplicates(subset=['Num_Acc', 'id_vehicule', 'num_veh'], keep='first')
    
    #enregistrement du fichier final
    combined_data.to_csv('data/processed/Accident_auto_combined.csv', index=False, encoding='utf-8')
    print(f"Combined export: {len(combined_data)} total records across all years")
else: print(f"Combined export: no record")
#pd.DataFrame([all_accidents]).to_csv('Accident_auto.csv', index=False, encoding='utf-8')  # ou 'ISO-8859-1' si besoin

Traitement des fichiers pour l'année 2023...
sep= ;
data/raw/caract-2023.csv ; utf-8
Essai avec encodage : utf-8
data/raw/caract-2023.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/lieux-2023.csv ; utf-8
Essai avec encodage : utf-8
data/raw/lieux-2023.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/usagers-2023.csv ; utf-8
Essai avec encodage : utf-8
data/raw/usagers-2023.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/vehicules-2023.csv ; utf-8
Essai avec encodage : utf-8
data/raw/vehicules-2023.csv ; utf-8
✅ Lecture réussie avec utf-8
    ✅Fusion réussie pour l'année 2023

Traitement des fichiers pour l'année 2022...
sep= ;
data/raw/carcteristiques-2022.csv ; utf-8
Essai avec encodage : utf-8
data/raw/carcteristiques-2022.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/lieux-2022.csv ; utf-8
Essai avec encodage : utf-8
data/raw/lieux-2022.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/usagers-2022.csv ; utf-8
Essai avec encodage : utf-8
data/raw/usagers-2022.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/vehicules-2022.csv ; utf-8
Essai avec encodage : utf-8
data/raw/vehicules-2022.csv ; utf-8
✅ Lecture réussie avec utf-8
    ✅Fusion réussie pour l'année 2022

Traitement des fichiers pour l'année 2021...
sep= ;
data/raw/carcteristiques-2021.csv ; utf-8
Essai avec encodage : utf-8
data/raw/carcteristiques-2021.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/lieux-2021.csv ; utf-8
Essai avec encodage : utf-8
data/raw/lieux-2021.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/usagers-2021.csv ; utf-8
Essai avec encodage : utf-8
data/raw/usagers-2021.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/vehicules-2021.csv ; utf-8
Essai avec encodage : utf-8
data/raw/vehicules-2021.csv ; utf-8
✅ Lecture réussie avec utf-8
    ✅Fusion réussie pour l'année 2021

Traitement des fichiers pour l'année 2020...
sep= ;
data/raw/caracteristiques-2020.csv ; utf-8
Essai avec encodage : utf-8
data/raw/caracteristiques-2020.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/lieux-2020.csv ; utf-8
Essai avec encodage : utf-8
data/raw/lieux-2020.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/usagers-2020.csv ; utf-8
Essai avec encodage : utf-8
data/raw/usagers-2020.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/vehicules-2020.csv ; utf-8
Essai avec encodage : utf-8
data/raw/vehicules-2020.csv ; utf-8
✅ Lecture réussie avec utf-8
    ✅Fusion réussie pour l'année 2020

Traitement des fichiers pour l'année 2019...
sep= ;
data/raw/caracteristiques-2019.csv ; utf-8
Essai avec encodage : utf-8
data/raw/caracteristiques-2019.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/lieux-2019.csv ; utf-8
Essai avec encodage : utf-8
data/raw/lieux-2019.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/usagers-2019.csv ; utf-8
Essai avec encodage : utf-8
data/raw/usagers-2019.csv ; utf-8
✅ Lecture réussie avec utf-8
sep= ;
data/raw/vehicules-2019.csv ; utf-8
Essai avec encodage : utf-8
data/raw/vehicules-2019.csv ; utf-8
✅ Lecture réussie avec utf-8
    ✅Fusion réussie pour l'année 2019

Traitement des fichiers pour l'année 2018...
sep= ,
data/raw/caracteristiques-2018.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 10: invalid continuation byte
data/raw/caracteristiques-2018.csv , cp1252
Essai avec encodage : cp1252
    ⚠️ Échec avec cp1252 : 'charmap' codec can't decode byte 0x90 in position 146267: character maps to <undefined>
data/raw/caracteristiques-2018.csv , iso-8859-1
Essai avec encodage : iso-8859-1
data/raw/caracteristiques-2018.csv , iso-8859-1
✅ Lecture réussie avec iso-8859-1
sep= ,
data/raw/lieux-2018.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux-2018.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers-2018.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers-2018.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules-2018.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules-2018.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2018
accident2018

Traitement des fichiers pour l'année 2017...
sep= ,
data/raw/caracteristiques-2017.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 7: invalid continuation byte
data/raw/caracteristiques-2017.csv , cp1252
Essai avec encodage : cp1252
    ⚠️ Échec avec cp1252 : 'charmap' codec can't decode byte 0x90 in position 187396: character maps to <undefined>
data/raw/caracteristiques-2017.csv , iso-8859-1
Essai avec encodage : iso-8859-1
data/raw/caracteristiques-2017.csv , iso-8859-1
✅ Lecture réussie avec iso-8859-1
sep= ,
data/raw/lieux-2017.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux-2017.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers-2017.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers-2017.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules-2017.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules-2017.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2017
accident2017

Traitement des fichiers pour l'année 2016...
sep= ,
data/raw/caracteristiques_2016.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe8 in position 16: invalid continuation byte
data/raw/caracteristiques_2016.csv , cp1252
Essai avec encodage : cp1252
    ⚠️ Échec avec cp1252 : 'charmap' codec can't decode byte 0x90 in position 214158: character maps to <undefined>
data/raw/caracteristiques_2016.csv , iso-8859-1
Essai avec encodage : iso-8859-1
data/raw/caracteristiques_2016.csv , iso-8859-1
✅ Lecture réussie avec iso-8859-1
sep= ,
data/raw/lieux_2016.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2016.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2016.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2016.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2016.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2016.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2016
accident2016

Traitement des fichiers pour l'année 2015...
sep= ,
data/raw/caracteristiques_2015.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe8 in position 16: invalid continuation byte
data/raw/caracteristiques_2015.csv , cp1252
Essai avec encodage : cp1252
    ⚠️ Échec avec cp1252 : 'charmap' codec can't decode byte 0x90 in position 183755: character maps to <undefined>
data/raw/caracteristiques_2015.csv , iso-8859-1
Essai avec encodage : iso-8859-1
data/raw/caracteristiques_2015.csv , iso-8859-1
✅ Lecture réussie avec iso-8859-1
sep= ,
data/raw/lieux_2015.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2015.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2015.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2015.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2015.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2015.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2015
accident2015

Traitement des fichiers pour l'année 2014...
sep= ,
data/raw/caracteristiques_2014.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 13: invalid continuation byte
data/raw/caracteristiques_2014.csv , cp1252
Essai avec encodage : cp1252
data/raw/caracteristiques_2014.csv , cp1252
✅ Lecture réussie avec cp1252
sep= ,
data/raw/lieux_2014.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2014.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2014.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2014.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2014.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2014.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2014
accident2014

Traitement des fichiers pour l'année 2013...
sep= ,
data/raw/caracteristiques_2013.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 16: invalid continuation byte
data/raw/caracteristiques_2013.csv , cp1252
Essai avec encodage : cp1252
data/raw/caracteristiques_2013.csv , cp1252
✅ Lecture réussie avec cp1252
sep= ,
data/raw/lieux_2013.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2013.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2013.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2013.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2013.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2013.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2013
accident2013

Traitement des fichiers pour l'année 2012...
sep= ,
data/raw/caracteristiques_2012.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 8: invalid continuation byte
data/raw/caracteristiques_2012.csv , cp1252
Essai avec encodage : cp1252
data/raw/caracteristiques_2012.csv , cp1252
✅ Lecture réussie avec cp1252
sep= ,
data/raw/lieux_2012.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2012.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2012.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2012.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2012.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2012.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2012
accident2012

Traitement des fichiers pour l'année 2011...
sep= ,
data/raw/caracteristiques_2011.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte
data/raw/caracteristiques_2011.csv , cp1252
Essai avec encodage : cp1252
data/raw/caracteristiques_2011.csv , cp1252
✅ Lecture réussie avec cp1252
sep= ,
data/raw/lieux_2011.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2011.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2011.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2011.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2011.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2011.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2011
accident2011

Traitement des fichiers pour l'année 2010...
sep= ,
data/raw/caracteristiques_2010.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 8: invalid continuation byte
data/raw/caracteristiques_2010.csv , cp1252
Essai avec encodage : cp1252
    ⚠️ Échec avec cp1252 : 'charmap' codec can't decode byte 0x90 in position 257236: character maps to <undefined>
data/raw/caracteristiques_2010.csv , iso-8859-1
Essai avec encodage : iso-8859-1
data/raw/caracteristiques_2010.csv , iso-8859-1
✅ Lecture réussie avec iso-8859-1
sep= ,
data/raw/lieux_2010.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2010.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2010.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2010.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2010.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2010.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2010
accident2010

Traitement des fichiers pour l'année 2009...
sep=
data/raw/caracteristiques_2009.csv 	 utf-8
Essai avec encodage : utf-8
data/raw/caracteristiques_2009.csv 	 utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/lieux_2009.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2009.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2009.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2009.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2009.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2009.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2009
accident2009

Traitement des fichiers pour l'année 2008...
sep= ,
data/raw/caracteristiques_2008.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xf4 in position 17: invalid continuation byte
data/raw/caracteristiques_2008.csv , cp1252
Essai avec encodage : cp1252
data/raw/caracteristiques_2008.csv , cp1252
✅ Lecture réussie avec cp1252
sep= ,
data/raw/lieux_2008.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2008.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2008.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2008.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2008.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2008.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2008
accident2008

Traitement des fichiers pour l'année 2007...
sep= ,
data/raw/caracteristiques_2007.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 1: invalid continuation byte
data/raw/caracteristiques_2007.csv , cp1252
Essai avec encodage : cp1252
data/raw/caracteristiques_2007.csv , cp1252
✅ Lecture réussie avec cp1252
sep= ,
data/raw/lieux_2007.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2007.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2007.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2007.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2007.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2007.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2007
accident2007

Traitement des fichiers pour l'année 2006...
sep= ,
data/raw/caracteristiques_2006.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xb0 in position 6: invalid start byte
data/raw/caracteristiques_2006.csv , cp1252
Essai avec encodage : cp1252
data/raw/caracteristiques_2006.csv , cp1252
✅ Lecture réussie avec cp1252
sep= ,
data/raw/lieux_2006.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2006.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2006.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2006.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2006.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2006.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2006
accident2006

Traitement des fichiers pour l'année 2005...
sep= ,
data/raw/caracteristiques_2005.csv , utf-8
Essai avec encodage : utf-8
    ⚠️ Échec avec utf-8 : 'utf-8' codec can't decode byte 0xe9 in position 13: invalid continuation byte
data/raw/caracteristiques_2005.csv , cp1252
Essai avec encodage : cp1252
data/raw/caracteristiques_2005.csv , cp1252
✅ Lecture réussie avec cp1252
sep= ,
data/raw/lieux_2005.csv , utf-8
Essai avec encodage : utf-8
data/raw/lieux_2005.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/usagers_2005.csv , utf-8
Essai avec encodage : utf-8
data/raw/usagers_2005.csv , utf-8
✅ Lecture réussie avec utf-8
sep= ,
data/raw/vehicules_2005.csv , utf-8
Essai avec encodage : utf-8
data/raw/vehicules_2005.csv , utf-8
✅ Lecture réussie avec utf-8
    ⚠️ Clé manquante pour la fusion avec id_vehicule : 'id_vehicule'
    ✅Fusion réussie SANS id_vehicule pour l'année 2005
accident2005
Combined export: 2800038 total records across all years

In [40]:
combined_data.head(50)

,Num_Acc,id_usager,id_vehicule,num_veh_x,place,catu,grav,sexe,an_nais,trajet,...,int,atm,col,adr,lat,long,secu,num_veh,env1,gps
0,202300000001,203 851 184,155 680 557,A01,1.0,1,4,1,1978.0,5.0,...,4,2.0,7.0,RUE DE RIVOLI,"48,86638600","2,32347100",NaN,NaN,NaN,NaN
1,202300000001,203 851 184,155 680 557,A01,1.0,1,4,1,1978.0,5.0,...,4,2.0,7.0,RUE DE RIVOLI,"48,86638600","2,32347100",NaN,NaN,NaN,NaN
2,202300000002,203 851 182,155 680 556,A01,1.0,1,1,2,1997.0,9.0,...,1,3.0,6.0,Avenue de Paris,"48,84547782","2,42868146",NaN,NaN,NaN,NaN
3,202300000002,203 851 183,155 680 556,A01,10.0,3,3,1,1997.0,9.0,...,1,3.0,6.0,Avenue de Paris,"48,84547782","2,42868146",NaN,NaN,NaN,NaN
4,202300000003,203 851 180,155 680 554,B01,1.0,1,3,1,1987.0,0.0,...,3,2.0,1.0,Avenue du Général Leclerc,"48,76240000","2,40655000",NaN,NaN,NaN,NaN
5,202300000003,203 851 180,155 680 554,B01,1.0,1,3,1,1987.0,0.0,...,3,2.0,1.0,Avenue du Général Leclerc,"48,76240000","2,40655000",NaN,NaN,NaN,NaN
6,202300000003,203 851 181,155 680 555,A01,1.0,1,1,2,1984.0,0.0,...,3,2.0,1.0,Avenue du Général Leclerc,"48,76240000","2,40655000",NaN,NaN,NaN,NaN
7,202300000003,203 851 181,155 680 555,A01,1.0,1,1,2,1984.0,0.0,...,3,2.0,1.0,Avenue du Général Leclerc,"48,76240000","2,40655000",NaN,NaN,NaN,NaN
8,202300000004,203 851 175,155 680 551,B01,2.0,2,1,2,2001.0,1.0,...,1,3.0,5.0,Rue de Paris,"48,73248432","2,44687575",NaN,NaN,NaN,NaN
9,202300000004,203 851 176,155 680 551,B01,1.0,1,1,2,1995.0,1.0,...,1,3.0,5.0,Rue de Paris,"48,73248432","2,44687575",NaN,NaN,NaN,NaN
10,202300000004,203 851 177,155 680 552,C01,1.0,1,1,1,1968.0,9.0,...,1,3.0,5.0,Rue de Paris,"48,73248432","2,44687575",NaN,NaN,NaN,NaN
11,202300000004,203 851 178,155 680 552,C01,2.0,2,4,1,1956.0,0.0,...,1,3.0,5.0,Rue de Paris,"48,73248432","2,44687575",NaN,NaN,NaN,NaN
12,202300000004,203 851 179,155 680 553,A01,1.0,1,1,1,1985.0,1.0,...,1,3.0,5.0,Rue de Paris,"48,73248432","2,44687575",NaN,NaN,NaN,NaN
13,202300000005,203 851 173,155 680 549,B01,1.0,1,4,2,2001.0,0.0,...,2,3.0,3.0,56bis Avenue Raspail,"48,78581000","2,49217000",NaN,NaN,NaN,NaN
14,202300000005,203 851 173,155 680 549,B01,1.0,1,4,2,2001.0,0.0,...,2,3.0,3.0,56bis Avenue Raspail,"48,78581000","2,49217000",NaN,NaN,NaN,NaN
15,202300000005,203 851 174,155 680 550,A01,1.0,1,1,1,2001.0,3.0,...,2,3.0,3.0,56bis Avenue Raspail,"48,78581000","2,49217000",NaN,NaN,NaN,NaN
16,202300000005,203 851 174,155 680 550,A01,1.0,1,1,1,2001.0,3.0,...,2,3.0,3.0,56bis Avenue Raspail,"48,78581000","2,49217000",NaN,NaN,NaN,NaN
17,202300000006,203 851 171,155 680 548,A01,10.0,3,4,1,2003.0,9.0,...,3,2.0,6.0,Avenue Gabriel Péri,"48,83717000","2,51361000",NaN,NaN,NaN,NaN
18,202300000006,203 851 172,155 680 548,A01,1.0,1,1,1,1962.0,5.0,...,3,2.0,6.0,Avenue Gabriel Péri,"48,83717000","2,51361000",NaN,NaN,NaN,NaN
19,202300000007,203 851 167,155 680 545,C01,1.0,1,1,1,1988.0,0.0,...,1,2.0,4.0,185 Boulevard Maxime Gorki,"48,78693219","2,36756095",NaN,NaN,NaN,NaN
20,202300000007,203 851 168,155 680 546,A01,4.0,2,4,2,1975.0,5.0,...,1,2.0,4.0,185 Boulevard Maxime Gorki,"48,78693219","2,36756095",NaN,NaN,NaN,NaN
21,202300000007,203 851 169,155 680 546,A01,1.0,1,1,1,1968.0,5.0,...,1,2.0,4.0,185 Boulevard Maxime Gorki,"48,78693219","2,36756095",NaN,NaN,NaN,NaN
22,202300000007,203 851 170,155 680 547,B01,1.0,1,1,2,1979.0,0.0,...,1,2.0,4.0,185 Boulevard Maxime Gorki,"48,78693219","2,36756095",NaN,NaN,NaN,NaN
23,202300000008,203 851 164,155 680 543,B01,4.0,2,4,2,2020.0,0.0,...,2,3.0,1.0,Route de Stains / Rue du Moulin Bateau,"48,78238000","2,49510000",NaN,NaN,NaN,NaN
24,202300000008,203 851 164,155 680 543,B01,4.0,2,4,2,2020.0,0.0,...,2,3.0,1.0,Route de Stains / Rue du Moulin Bateau,"48,78238000","2,49510000",NaN,NaN,NaN,NaN
25,202300000008,203 851 165,155 680 543,B01,1.0,1,1,1,1980.0,0.0,...,2,3.0,1.0,Route de Stains / Rue du Moulin Bateau,"48,78238000","2,49510000",NaN,NaN,NaN,NaN
26,202300000008,203 851 165,155 680 543,B01,1.0,1,1,1,1980.0,0.0,...,2,3.0,1.0,Route de Stains / Rue du Moulin Bateau,"48,78238000","2,49510000",NaN,NaN,NaN,NaN
27,202300000008,203 851 166,155 680 544,A01,1.0,1,1,1,1981.0,0.0,...,2,3.0,1.0,Route de Stains / Rue du Moulin Bateau,"48,78238000","2,49510000",NaN,NaN,NaN,NaN
28,202300000008,203 851 166,155 680 544,A01,1.0,1,1,1,1981.0,0.0,...,2,3.0,1.0,Route de Stains / Rue du Moulin Bateau,"48,78238000","2,49510000",NaN,NaN,NaN,NaN
29,202300000009,203 851 162,155 680 541,A01,1.0,1,1,1,1988.0,0.0,...,3,8.0,3.0,Avenue de la République,"48,76240184","2,40690601",NaN,NaN,NaN,NaN
30,202300000009,203 851 162,155 680 541,A01,1.0,1,1,1,1988.0,0.0,...,3,8.0,3.0,Avenue de la République,"48,76240184","2,40690601",NaN,NaN,NaN,NaN
31,202300000009,203 851 163,155 680 542,B01,1.0,1,4,1,2003.0,0.0,...,3,8.0,3.0,Avenue de la République,"48,76240184","2,40690601",NaN,NaN,NaN,NaN
32,202300000009,203 851 163,155 680 542,B01,1.0,1,4,1,2003.0,0.0,...,3,8.0,3.0,Avenue de la République,"48,76240184","2,40690601",NaN,NaN,NaN,NaN
33,202300000010,203 851 160,155 680 540,B01,1.0,1,1,1,1999.0,5.0,...,1,2.0,6.0,Boulevard de Friedberg,"48,83266000","2,54378000",NaN,NaN,NaN,NaN
34,202300000010,203 851 161,155 680 540,B01,10.0,3,4,1,1953.0,5.0,...,1,2.0,6.0,Boulevard de Friedberg,"48,83266000","2,54378000",NaN,NaN,NaN,NaN
35,202300000011,203 851 156,155 680 538,A01,2.0,2,1,1,2010.0,5.0,...,9,2.0,3.0,A3,"48,99572240","2,51560628",NaN,NaN,NaN,NaN
36,202300000011,203 851 157,155 680 538,A01,1.0,1,4,2,1977.0,5.0,...,9,2.0,3.0,A3,"48,99572240","2,51560628",NaN,NaN,NaN,NaN
37,202300000011,203 851 158,155 680 539,B01,2.0,2,4,2,1997.0,5.0,...,9,2.0,3.0,A3,"48,99572240","2,51560628",NaN,NaN,NaN,NaN
38,202300000011,203 851 159,155 680 539,B01,1.0,1,1,1,1996.0,5.0,...,9,2.0,3.0,A3,"48,99572240","2,51560628",NaN,NaN,NaN,NaN
39,202300000012,203 851 154,155 680 536,B01,1.0,1,1,1,2003.0,5.0,...,3,8.0,3.0,Rue du Docteur Vaillant / A4,"48,83611000","2,56460000",NaN,NaN,NaN,NaN
40,202300000012,203 851 154,155 680 536,B01,1.0,1,1,1,2003.0,5.0,...,3,8.0,3.0,Rue du Docteur Vaillant / A4,"48,83611000","2,56460000",NaN,NaN,NaN,NaN
41,202300000012,203 851 155,155 680 537,A01,1.0,1,4,1,1982.0,5.0,...,3,8.0,3.0,Rue du Docteur Vaillant / A4,"48,83611000","2,56460000",NaN,NaN,NaN,NaN
42,202300000012,203 851 155,155 680 537,A01,1.0,1,4,1,1982.0,5.0,...,3,8.0,3.0,Rue du Docteur Vaillant / A4,"48,83611000","2,56460000",NaN,NaN,NaN,NaN
43,202300000013,203 851 152,155 680 534,A01,1.0,1,1,1,1994.0,1.0,...,1,2.0,2.0,Avenue Ambroise Croizat,"48,95859534","2,41581470",NaN,NaN,NaN,NaN
44,202300000013,203 851 153,155 680 535,B01,1.0,1,4,1,1992.0,1.0,...,1,2.0,2.0,Avenue Ambroise Croizat,"48,95859534","2,41581470",NaN,NaN,NaN,NaN
45,202300000014,203 851 151,155 680 533,A01,1.0,1,4,1,1977.0,0.0,...,6,1.0,6.0,Carrefour Lindbergh,"48,94211000","2,42916000",NaN,NaN,NaN,NaN
46,202300000015,203 851 147,155 680 531,A01,1.0,1,1,1,2001.0,5.0,...,1,2.0,2.0,Avenue Galliéni,"48,90631671","2,48228681",NaN,NaN,NaN,NaN
47,202300000015,203 851 148,155 680 532,B01,3.0,2,1,1,2022.0,0.0,...,1,2.0,2.0,Avenue Galliéni,"48,90631671","2,48228681",NaN,NaN,NaN,NaN
48,202300000015,203 851 149,155 680 532,B01,2.0,2,1,1,1998.0,5.0,...,1,2.0,2.0,Avenue Galliéni,"48,90631671","2,48228681",NaN,NaN,NaN,NaN
49,202300000015,203 851 150,155 680 532,B01,1.0,1,4,1,1999.0,0.0,...,1,2.0,2.0,Avenue Galliéni,"48,90631671","2,48228681",NaN,NaN,NaN,NaN

In [43]:
print(combined_data.duplicated().sum())

2858